### ISSUE TITLE
Microsoft Edge browser can no longer connect to the net.

### ISSUE THREAD

**Issue by globetrotterdk** [nomadbsd/handbook#13]
The subject tells most of the story as I know it. The browser shows the following:

![edge_error](https://user-images.githubusercontent.com/16561375/155113966-b89302fa-f139-4eb2-b9d3-e191f54594d3.png)

I have also noted the following in /var/log/messages:

`Feb 22 10:10:36 NomadBSD kernel: linux: jid 0 pid 4442 (ThreadPoolForeg): syscall inotify_init not implemented
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4442 (CrShutdownDetec): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4460 (ThreadPoolSingl): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4442 (VideoCaptureThr): unsupported socket(AF_NETLINK, 3, NETLINK_KOBJECT_UEVENT)
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4461 (BrowserWatchdog): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4442 (BrowserWatchdog): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)syscall inotify_init not implemented
Feb 22 10:10:37 NomadBSD kernel: 
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4462 (BrowserWatchdog): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4463 (CacheThread_Blo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4464 (CacheThread_Blo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4465 (CacheThread_Blo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4466 (CacheThread_Blo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:37 NomadBSD syslogd: last message repeated 3 times
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4467 (CacheThread_Blo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:37 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:37 NomadBSD syslogd: last message repeated 1 times
Feb 22 10:10:38 NomadBSD kernel: linux: jid 0 pid 4468 (BatteryStatusNo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:42 NomadBSD kernel: linux: jid 0 pid 4442 (BatteryStatusNo): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:42 NomadBSD kernel: linux: jid 0 pid 4470 (BatteryStatusNo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:42 NomadBSD kernel: linux: jid 0 pid 4442 (BatteryStatusNo): unsupported socket(AF_NETLINK, 3, NETLINK_KOBJECT_UEVENT)
Feb 22 10:10:42 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:42 NomadBSD kernel: linux: jid 0 pid 4442 (BatteryStatusNo): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:42 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)
Feb 22 10:10:43 NomadBSD syslogd: last message repeated 6 times
Feb 22 10:10:45 NomadBSD kernel: linux: jid 0 pid 4476 (BatteryStatusNo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:45 NomadBSD kernel: linux: jid 0 pid 4477 (BatteryStatusNo): unsupported prctl PR_SET_NO_NEW_PRIVS
Feb 22 10:10:45 NomadBSD kernel: linux: jid 0 pid 4461 (ThreadPoolForeg): unsupported socket(AF_NETLINK, 3, NETLINK_ROUTE)`

**Comment by mrclksr** [comment]
Sorry, this has nothing to do with the handbook.
