### ISSUE TITLE
Internationalization gone crazy after install to SSD.

### ISSUE THREAD

**Issue by globetrotterdk** [nomadbsd/handbook#5]
I am using a Danish keyboard, but everything else was in English (as I want it), when using a USB drive. However, now that I installed NomadBSD to my computer, the manage user accounts all of a sudden set the login class to da_DK. I have since changed this to en_US (my preferred setting). I have also tried to set the environment to
`LC_ALL to 'en_US.UTF-8'`
 in ~/.profile however, now I have a mix of English and Danish as can be seen in the screenshot.
![Screenshot_2022-01-29_17-34-45](https://user-images.githubusercontent.com/16561375/151667269-0c567627-88c6-4111-bdd2-e740ae89389e.png)
.

**Comment by mrclksr** [comment]
Run `xdg-user-dirs-update` to adjust the names of standard dirs to the current locale.

**Comment by globetrotterdk** [comment]
> Run `xdg-user-dirs-update` to adjust the names of standard dirs to the current locale.

No change after a reboot...

**Comment by mrclksr** [comment]
`rm ~/.config/user-dirs.dirs && xdg-user-dirs-update`

**Comment by globetrotterdk** [comment]
> `rm ~/.config/user-dirs.dirs && xdg-user-dirs-update`

No change after a reboot.

**Comment by mrclksr** [comment]
> No change after a reboot.

That's odd. Run `xdg-user-dirs-update --force`. Is there any output?

Regarding the Danish menu item: Change it via *Thunar* -> *Edit* -> *Configure custom actions...*

**Comment by globetrotterdk** [comment]
> 
Done

`~> xdg-user-dirs-update --force
Moving DESKTOP directory from Skrivebord to Desktop
Moving DOWNLOAD directory from Hentet to Downloads
Moving TEMPLATES directory from Skabeloner to Templates
Moving PUBLICSHARE directory from Offentligt to Public
Moving DOCUMENTS directory from Dokumenter to Documents
Moving MUSIC directory from Musik to Music
Moving PICTURES directory from Billeder to Pictures
Moving VIDEOS directory from Videoklip to Videos
`
It seems to have worked. I migrated any contents and then sent the Danish versions of the folders to the trash.

Done.
I appreciate the help. Everything seems fine now.

**Comment by mrclksr** [comment]
Excellent!
